[package]
name = "ray_tracing"
version = "0.1.0"
authors = ["Kahlil Oppenheimer <kahliloppenheimer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "1.1.0"
png = "0.15.3"
